export class incidente{
    constructor(
        incidente_id,
        user,
        titulo,
        descripcion,
        tipo,
        lugar,
        fecha,
        lat,
        lng,
        descripcionCompleta,
        evidencia1,
        evidencia2,
        evidencia3,
        user_id,
        validacion_status
        )
    {
        this.incidente_id=incidente_id
        this.user=user;
        this.titulo=titulo;
        this.descripcion=descripcion;
        this.tipo=tipo;
        this.lugar=lugar;
        this.fecha=fecha;
        this.lat=lat;
        this.lng=lng;
        this.descripcionCompleta=descripcionCompleta;
        this.evidencia1=evidencia1;
        this.evidencia2=evidencia2;
        this.evidencia3=evidencia3;
        this.user_id=user_id;
        this.validacion_status=validacion_status
    }
}
