import { incidente } from "./incidente"
export class incidenteValidado extends incidente{
    constructor(user,
        titulo,
        descripcion,
        tipo,
        lugar,
        fecha,
        lat,
        lng,
        descripcionCompleta,
        evidencia1,
        evidencia2,
        evidencia3,
        validacion,
        comentariosAdmin,
        mensajeValidacion,
        faltaEvidencia
        ){
        super(
            user,
            titulo,
            descripcion,
            tipo,
            lugar,
            fecha,
            lat,
            lng,
            descripcionCompleta,
            evidencia1,
            evidencia2,
            evidencia3
        )
        this.validacion=validacion
        this.comentariosAdmin=comentariosAdmin
        this.mensajeValidacion=mensajeValidacion 
        this.faltaEvidencia=faltaEvidencia
    }
}
